// Cross-validate HfBpeTokenizer against ground-truth fixtures generated by
// HuggingFace's Python `tokenizers` library
// (tools/text/dump_hf_tokenizer_fixtures.py). This catches drift in the C++
// BPE algorithm relative to the canonical implementation.
#include "cverl/text/hf_bpe_tokenizer.h"

#include <nlohmann/json.hpp>

#include <fstream>
#include <iostream>
#include <stdexcept>
#include <string>
#include <vector>

namespace {

void require(bool cond, const std::string& msg) {
  if (!cond) {
    throw std::runtime_error(msg);
  }
}

std::string vec_repr(const std::vector<int32_t>& v) {
  std::string s = "[";
  for (size_t i = 0; i < v.size(); ++i) {
    if (i) s += ", ";
    s += std::to_string(v[i]);
  }
  s += "]";
  return s;
}

}  // namespace

int main(int argc, char** argv) {
  using cverl::text::HfBpeTokenizer;
  using cverl::text::HfBpeTokenizerOptions;

  // Default fixture path is relative to the project source root, set by
  // CMake at build time. Allow CLI overrides for ad-hoc runs against real
  // tokenizers.
#ifndef CVERL_PROJECT_SOURCE_DIR
#define CVERL_PROJECT_SOURCE_DIR "."
#endif
  std::string tokenizer_json =
      std::string(CVERL_PROJECT_SOURCE_DIR) + "/tests/text/fixtures/synthetic/tokenizer.json";
  std::string fixtures_json =
      std::string(CVERL_PROJECT_SOURCE_DIR) + "/tests/text/fixtures/synthetic/fixtures.json";
  if (argc >= 2) tokenizer_json = argv[1];
  if (argc >= 3) fixtures_json = argv[2];

  try {
    HfBpeTokenizerOptions opts;
    opts.tokenizer_json_path = tokenizer_json;
    HfBpeTokenizer tok(opts);

    require(tok.vocab_size() > 256, "synthetic tokenizer has merged tokens");
    require(tok.name() == "hf-bpe", "tokenizer name");

    // Smoke: pad/eos discovery from added_tokens.
    require(tok.pad_id() >= 0, "synthetic tokenizer reports a pad id");
    require(tok.eos_id() >= 0, "synthetic tokenizer reports an eos id");

    // Cross-validate every fixture against HF Python ground truth.
    std::ifstream in(fixtures_json);
    if (!in.is_open()) {
      throw std::runtime_error("fixture file not found: " + fixtures_json);
    }
    nlohmann::json fixtures;
    in >> fixtures;
    require(fixtures.is_array() && !fixtures.empty(), "fixtures.json non-empty array");

    int passed = 0;
    int failed = 0;
    for (const auto& fx : fixtures) {
      std::string text = fx.value("text", std::string{});
      std::vector<int32_t> expected_ids = fx.at("ids").get<std::vector<int32_t>>();
      std::string expected_decoded = fx.value("decoded", std::string{});

      auto got_ids = tok.encode(text);
      if (got_ids != expected_ids) {
        std::cerr << "encode mismatch for text=\"" << text << "\":\n";
        std::cerr << "  expected " << vec_repr(expected_ids) << "\n";
        std::cerr << "  got      " << vec_repr(got_ids) << "\n";
        ++failed;
        continue;
      }
      auto got_decoded = tok.decode(got_ids, /*skip_special=*/false);
      if (got_decoded != expected_decoded) {
        std::cerr << "decode mismatch for text=\"" << text << "\":\n";
        std::cerr << "  expected \"" << expected_decoded << "\"\n";
        std::cerr << "  got      \"" << got_decoded << "\"\n";
        ++failed;
        continue;
      }
      ++passed;
    }

    if (failed > 0) {
      throw std::runtime_error(std::to_string(failed) + " of " +
                               std::to_string(passed + failed) +
                               " HF fixtures failed");
    }

    // Truncation, BOS / EOS plumbing.
    {
      cverl::text::EncodeOptions enc_opts;
      enc_opts.add_eos = true;
      auto ids = tok.encode("Hello world", enc_opts);
      require(!ids.empty(), "encode with EOS non-empty");
      require(ids.back() == tok.eos_id(), "EOS appended");
    }
    {
      cverl::text::EncodeOptions enc_opts;
      enc_opts.max_tokens = 2;
      auto ids = tok.encode("Hello world", enc_opts);
      require(static_cast<int32_t>(ids.size()) == 2, "max_tokens caps");
    }

    // Decode skip_special drops added_tokens.
    {
      auto ids = tok.encode("<|endoftext|>");
      require(ids.size() == 1, "single-token special encoding");
      require(tok.decode(ids, /*skip_special=*/true).empty(), "skip_special hides specials");
      require(tok.decode(ids, /*skip_special=*/false) == "<|endoftext|>",
              "non-skip_special preserves specials");
    }

    std::cout << "hf-bpe tokenizer fixtures passed (" << passed << " probes)\n";
    return 0;
  } catch (const std::exception& e) {
    std::cerr << "test_hf_bpe_tokenizer failed: " << e.what() << "\n";
    return 1;
  }
}
