#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "${ROOT_DIR}"

MODEL_DIR="${MODEL_DIR:-${ROOT_DIR}/../models/Qwen3-30B-A3B}"
BUILD_DIR="${BUILD_DIR:-${ROOT_DIR}/build-h20-ppo-8gpu-zw}"

CUDA_VISIBLE_DEVICES="${CUDA_VISIBLE_DEVICES:-0,1,2,3,4,5,6,7}"
DP_SIZE="${DP_SIZE:-1}"
PP_SIZE="${PP_SIZE:-2}"
CP_SIZE="${CP_SIZE:-1}"
TP_SIZE="${TP_SIZE:-2}"
EP_SIZE="${EP_SIZE:-2}"
SP_SIZE="${SP_SIZE:-1}"
LOCAL_WORLD_SIZE="${LOCAL_WORLD_SIZE:-8}"
LAYERS="${LAYERS:-4}"
PROMPT_LEN="${PROMPT_LEN:-8}"
RESPONSE_LEN="${RESPONSE_LEN:-8}"
MICRO_BATCHES="${MICRO_BATCHES:-4}"
GRAD_ACCUM_STEPS="${GRAD_ACCUM_STEPS:-1}"
STEPS="${STEPS:-1}"
TRAIN_MODE="${TRAIN_MODE:-sft}"
JSONL_INPUT="${JSONL_INPUT:-${ROOT_DIR}/data/gsm8k-train-bench.jsonl}"
JSONL_MAX_EXAMPLES="${JSONL_MAX_EXAMPLES:-8}"
TOKENIZER_JSON="${TOKENIZER_JSON:-${MODEL_DIR}/tokenizer.json}"
METRICS_CSV="${METRICS_CSV:-${ROOT_DIR}/build/metrics/qwen3_30b_a3b_${TRAIN_MODE}_dp${DP_SIZE}_pp${PP_SIZE}_cp${CP_SIZE}_tp${TP_SIZE}_ep${EP_SIZE}_sp${SP_SIZE}_steps${STEPS}.csv}"
ID_PREFIX="${ID_PREFIX:-/tmp/cverl_qwen3_30b_a3b_moe_parallel}"

mkdir -p "$(dirname "${METRICS_CSV}")"
cmake --build "${BUILD_DIR}" --target qwen3_5_pp_tp_ppo_trainer -j "${JOBS:-8}"

common_env=(
  CUDA_VISIBLE_DEVICES="${CUDA_VISIBLE_DEVICES}"
  BUILD_DIR="${BUILD_DIR}"
  DP_SIZE="${DP_SIZE}"
  PP_SIZE="${PP_SIZE}"
  CP_SIZE="${CP_SIZE}"
  TP_SIZE="${TP_SIZE}"
  EP_SIZE="${EP_SIZE}"
  SP_SIZE="${SP_SIZE}"
  LOCAL_WORLD_SIZE="${LOCAL_WORLD_SIZE}"
  LAYERS="${LAYERS}"
  PROMPT_LEN="${PROMPT_LEN}"
  RESPONSE_LEN="${RESPONSE_LEN}"
  MICRO_BATCHES="${MICRO_BATCHES}"
  GRAD_ACCUM_STEPS="${GRAD_ACCUM_STEPS}"
  STEPS="${STEPS}"
  TRAIN_MODE="${TRAIN_MODE}"
  LR="${LR:-1e-8}"
  MAX_GRAD_NORM="${MAX_GRAD_NORM:-1.0}"
  MASTER_WEIGHTS="${MASTER_WEIGHTS:-false}"
  DP_SHARD_OPTIMIZER="${DP_SHARD_OPTIMIZER:-false}"
  MEASURE_PARAM_DELTA="${MEASURE_PARAM_DELTA:-true}"
  DTYPE="${DTYPE:-bfloat16}"
  DP_GRAD_COMM_DTYPE="${DP_GRAD_COMM_DTYPE:-bfloat16}"
  TP_GRAD_COMM_DTYPE="${TP_GRAD_COMM_DTYPE:-bfloat16}"
  TOKENIZER_JSON="${TOKENIZER_JSON}"
  METRICS_CSV="${METRICS_CSV}"
  ID_PREFIX="${ID_PREFIX}"
)

if [[ "${TRAIN_MODE}" == "sft" ]]; then
  common_env+=(
    JSONL_INPUT="${JSONL_INPUT}"
    JSONL_MAX_EXAMPLES="${JSONL_MAX_EXAMPLES}"
  )
fi

env "${common_env[@]}" tools/distributed/run_qwen_pp_tp_ppo_trainer.sh "${MODEL_DIR}"
